### ISSUE TITLE
Call to a member function getKey() on string 

### ISSUE THREAD

**Issue by kishanpatel963** [shanmuga3/laravel-entrust#2]
when i used attechPermission at that time it is shoing me this error

**Comment by kishanpatel963** [comment]
$role = new Role();
        $role->name = $request->input('role_name');
        $role->display_name = $request->input('role_display_name');
        $role->description = $request->input('role_description');
        $role->save();

        $permission = array();
        $permission = $request->role_permission;
      
        if(!is_null($permission)){
            foreach ($permission as $key => $value) {
              $role->attachPermission($value);
            }
        }

**Comment by shanmuga3** [comment]
This issue is fixed, You can use master source to get updated, But My Suggession is to use sync permission, it will also detach unchecked permission. It will clean and easy to understand.

`$permission = $request->role_permission ?? [];`
`$permissions = Permission::whereIn('id',$permission)->get();`
`$role->permissions()->sync($permissions);`
